version: '3'

volumes:
  pg_data_production:
  static_volume:


services:
  db:
    image: postgres:13.10
    restart: on-failure
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: idledrunk/taski_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/backend_static

  frontend:
    image: idledrunk/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: idledrunk/taski_gateway
    env_file: .env
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
